// Arabic messages for Blockly
var MSG = {
  // Main Interface
  title: "ArduinOman IDE",
  blocks: "الكتل",
  
  // Button Tooltips
  linkTooltip: "حفظ وربط الكتل.",
  runTooltip: "تشغيل البرنامج.",
  trashTooltip: "تجاهل جميع الكتل.",
  uploadTooltip: "رفع الكود إلى الأردوينو",
  myBtnTooltip: "الأمثلة",
  BuyTooltip: "شراء",
  BoardTooltip: "اللوحة",
  saveXMLTooltip: "حفظ الكتل",
  loadXMLTooltip: "تحميل الكتل", 
  copycodeTooltip: "نسخ كود الأردوينو",

  // Categories
  catLogic: "المنطق",
  catLoops: "الحلقات",
  catMath: "الرياضيات",
  catText: "النص",
  catTime: "الوقت",
  catGenericTime: "الوقت العام",
  catRTCDS1302: "RTC DS1302",
  catRTCDS3231: "RTC DS3231",
  catInterruptExt: "المقاطعات",
  catDivers: "متنوع",
  catAllVar: "المتغيرات",
  catVariables: "المتغيرات",
  catArray: "المصفوفات",
  catString: "النصوص",
  catFunctions: "الدوال",
  catInOut: "الإدخال/الإخراج",
  catDigital: "رقمي",
  catAnalog: "تماثلي",
  catCommunication: "الاتصالات",
  catSerialAll: "المسلسل",
  catSerial: "مسلسل",
  catSerial1: "مسلسل 1",
  catSoftSerial: "مسلسل برمجي",
  catBTAll: "بلوتوث",
  catBTSerial1: "بلوتوث مسلسل 1",
  catBTSoftSerial: "بلوتوث مسلسل برمجي",
  catRemoteIR: "التحكم عن بعد",
  catWIFI: "واي فاي",
  catWIFISerial1: "واي فاي مسلسل 1",
  catWIFISoftSerial: "واي فاي مسلسل برمجي",
  catIOT: "إنترنت الأشياء",
  catMQTTWifi: "MQTT واي فاي",
  catRF: "الترددات اللاسلكية",
  catRF24L01: "NRF24L01",
  catStorage: "التخزين",
  catEEprom: "EEPROM",
  catmicroSD: "مايكرو إس دي",
  catMotors: "المحركات",
  catMotorMRT: "محركات MRT",
  catServo: "سيرفو",
  catServoRot: "سيرفو مستمر",
  catStepper28BYJ: "Stepper 28BYJ",
  catStepper: "Stepper",
  catSimpleSensorsALL: "المستشعرات البسيطة",
  catSimpleSensors: "مستشعرات بسيطة 1",
  catSimpleSensors2: "مستشعرات بسيطة 2",
  catSimpleSensors3: "مستشعرات بسيطة 3",
  catOtherSensors: "مستشعرات أخرى",
  catRotaryEncoder: "المشفر الدوراني",
  catCCS811: "CCS811",
  catRFID: "RFID",
  catAPDS9960: "APDS9960",
  catGPS: "GPS",
  catCamera: "الكاميرا",
  catTCS3200: "TCS3200",
  catTCS34725: "TCS34725",
  catKeypad: "لوحة المفاتيح",
  catADXL345: "ADXL345",
  catHMC5883: "HMC5883",
  catds18b20: "DS18B20",
  catSimpleActuators: "المشغلات البسيطة",
  catOtherActuators: "مشغلات أخرى",
  catRadioTEA5767: "راديو TEA5767",
  catDFPlayerMP3: "DFPlayer MP3",
  catYK5300MP3: "YK5300 MP3",
  catDisplay: "العرض",
  catSerialLCD_I2C: "شاشة LCD I2C",
  catTM1637: "TM1637",
  catTM1638: "TM1638",
  catST7735: "شاشة ST7735",
  catNEXTION: "شاشة NEXTION",
  catMAX7219_LM: "MAX7219 مصفوفة",
  catMAX7219_7D: "MAX7217 7 أرقام",
  catLedStrip: "شريط LED",
  catVision: "الرؤية",
  catPixy2: "Pixy2",
  catMuVision: "Mu Vision",
  catOtto: "روبوت أوتو",

  // Text Variables
  textVariable: "نص",
  listVariable: "قائمة",

  // Messages
  badXml: "خطأ في تحليل XML:\n%1\n\nاختر 'موافق' للتخلي عن التغييرات أو 'إلغاء' لمواصلة تحرير XML.",
  badCode: "خطأ في البرنامج:\n%1",
  timeout: "تم تجاوز الحد الأقصى لعدد التكرارات المسموح به.",
  discard: "حذف جميع %1 كتلة؟",
  linkAlert: "شارك كتلك باستخدام هذا الرابط:\n\n%1",
  hashError: "عذراً، '%1' لا يتوافق مع أي برنامج محفوظ.",
  xmlError: "تعذر تحميل ملفك المحفوظ. ربما تم إنشاؤه بإصدار مختلف من Blockly؟",
  loadError: "تعذر تحميل ملفك المحفوظ. ربما تم إنشاؤه بإصدار مختلف من Blockly؟",
  httpRequestError: "كانت هناك مشكلة في الطلب.",

  // Warning Messages
  warningBadBlock: "كتلة بها مشكلة:",
  warningPleaseFix: "يرجى إصلاح الكتلة:",

  // Time
  timeout: "انتهى الوقت المسموح للتشغيل."
};